### ISSUE TITLE
Error in header filename

### ISSUE THREAD

**Issue by AdChildren** [brettmcalpine/PowerFlex4m#1]
Hi,

I got an error in PowerFlex4m.h on line 18,  when i tried to compile it with Arduino IDE.

Changing #include `"arduino.h"` by `#include "Arduino.h"`, seems to resolve the problem.

**Comment by brettmcalpine** [comment]
Thanks for the fix. Something I hadn't tested yet.

**Comment by AdChildren** [comment]
You're welcome ! And besides, this library is really great, it saves me a lot of work;)
